services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: >
      sh -c "
        ollama serve &
        until ollama list >/dev/null 2>&1; do
          sleep 2
        done
        ollama pull qwen3:4b-instruct
        wait
      "


  postgres:
    image: pgvector/pgvector:pg15
    container_name: legal_postgres
    environment:
      POSTGRES_USER: legal
      POSTGRES_PASSWORD: legalpass
      POSTGRES_DB: legal_rag
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  neo4j:
    image: neo4j:5.26
    container_name: legal_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_server_memory_heap_initial__size: 1G
      NEO4J_server_memory_heap_max__size: 1G
      NEO4J_server_memory_pagecache_size: 512M
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/import
    restart: unless-stopped

volumes:
  ollama:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  neo4j_import: